### ISSUE TITLE
Crash when placing an attuned Redstone Receiver

### ISSUE THREAD

**Issue by permdaddy** [Shukaro/Artifice#119]
http://pastebin.com/4yi6VZDy

On Modderation:FYAD server.

**Comment by Shukaro** [comment]
Is the server running cauldron? If so which version?

**Comment by permdaddy** [comment]
KCauldron 1448

Also, I am unable to make anything other than a very damaged anvil for some
reason, and that was what I attuned it with. Don't know if that could be
related.

**Comment by permdaddy** [comment]
I made two receivers and one transmitter. All were set to 'Mob' frequency. (is that supposed to be a number?)

I placed one receiver, crashed to desktop.

Came back, placed a second one and crashed again. 

Then I broke and trashed those blocks. 

Everything was in the overworld. Never placed the transmitter.

**Comment by Shukaro** [comment]
Should be fixed by 46a4d7bf39d3f2f726b5d0de056e758475139578

**Comment by sandalle** [comment]
I get [this client crash](http://pastebin.com/g9h7kb29) after updating to Artifice-1.7.10-[1.1.5R-397](http://minecraft.curseforge.com/mc-mods/223174-artifice/files/2248640) and trying to place a Redstone Transmitter attuned to "Mob" in a vanilla Anvil for the cost of five experience levels each on [Modderation: Permabanned](http://www.technicpack.net/modpack/details/modderation-permabanned-edition.449941) (using updates from [Modderation: Permabanned 1.1.5](https://github.com/mechaet/ModderationConfigs/pull/30)).

I had not placed a Redstone Receiver yet, I was placing the Redstone Transmitter first. If it matters, I did not craft these but gave them to myself:
```
[14:30:35 INFO]: [sandalle: Given [Unattuned Redstone Receiver] * 1 to sandalle]
[14:30:49 INFO]: [sandalle: Given [Unattuned Redstone Transmitter] * 1 to sandalle]
[14:31:35 INFO]: [sandalle: Given [Unattuned Redstone Receiver] * 1 to sandalle]
```

When I try to rejoin the game, I get [this client crash](http://pastebin.com/RttEm3xB) with a different error. I will wipe this test world and try again with a number instead of the text "Mob".

**Comment by Shukaro** [comment]
Try it with 67c37d2ba9c3da33af31d39121e9754fa3c460c4

also the name does not matter in the slightest

**Comment by sandalle** [comment]
I'm able to place both the Redstone Transmitter and Redstone Receiver attuned to "Mob" using [1.1.5R-398](http://minecraft.curseforge.com/mc-mods/223174-artifice/files/2248647), thanks. :)

**Comment by sandalle** [comment]
[1.1.5R-399](http://minecraft.curseforge.com/mc-mods/223174-artifice/files/2248653) also works with Cauldron, thank you. :)
