### ISSUE TITLE
Chisle 2 support

### ISSUE THREAD

**Issue by sircrimer** [Shukaro/Artifice#98]
Hi,

it would be nice if you could add support for Chisle 2.
Thx
sircrimer

**Comment by enkryptor** [comment]
Chisel 2 just adds a bunch of decorative blocks, there is nothing other mods can do to support it.

**Comment by Revemohl** [comment]
Artifice adds marble though, which used to be compatible with Chisel's marble (though the chisel item itself) before version 2.3, where it added a new GUI. I think limestone was also supported by that, though the conversion was one-way only.

**Comment by jermangarc** [comment]
You could probably do this using ModTweaker or BcMod.

**Comment by enkryptor** [comment]
AFAIK Artifice does add marble to the Forge ore dictionary. It might be Chisel's issue if it doesn't use the dictionary to see what is marble actually.

**Comment by sircrimer** [comment]
Well Chisel uses its own and bluepower marble. 
I'll go ask the Chisle dev about the oredict.

I also found Artifice Chisle compat crashing during loading. 
http://pastebin.com/5BAWG3wh

**Comment by Revemohl** [comment]
My guess is that the API change in 2.3 was so big it broke the compatibility with what Artifice used. You can even see in the startup log that Artifice can't load the Chisel module.

**Comment by eriniki** [comment]
I'd been meaning to open an issue for this a week or so ago myself (oops!). Artifice had Chisel compatibility (IIRC only for Marble registration) back in 1.6.4, however Chisel was orphaned after 1.6.4, ported to 1.7.2 by Asie then maintained and updated to 1.7.10 by Pokefenn, who then stopped around Sept last year. After that, it was picked up by TheCricket (and others) and renamed Chisel 2 - which included renaming the entire mod namespace. 

When Artifice loads its Chisel compatibility it throws the pastebin error @sircrimer linked if/when it fails to find the right class to load based off the old namespace, which if using Chisel 2 it always will since the namespace has changed.

From what I've looked into it seems like it might just need a change at [line #20](https://github.com/Shukaro/Artifice/blob/master/src/main/java/shukaro/artifice/compat/Chisel.java#L20) of Artifice/src/main/java/shukaro/artifice/compat/Chisel.java to replace the old namespace of "`info.jbcs.minecraft.chisel.ChiselBlocks`" with "`com.cricketcraft.chisel.init.ChiselBlocks`" - that is, if compatibility with the out-of-date 1.7 Chisel is no longer needed, haha.

**Comment by Shukaro** [comment]
Fixed by ec0ed70a67e1e57b634971a580358aa7ccd8d95f
